/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractState = State;

export interface State {
  balances: {
    [k: string]: number;
  };
  canEvolve?: boolean | null;
  evolve?: string | null;
  name?: string | null;
  owner: string;
  ticker: string;
}
