/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type View = Balance | BalanceResult;

export interface Balance {
  target: string;
}
export interface BalanceResult {
  balance: number;
  target: string;
  ticker: string;
}
