/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractError =
  | {
      data: string;
      kind: 'RuntimeError';
    }
  | {
      kind: 'TransferAmountMustBeHigherThanZero';
    }
  | {
      kind: 'IDontLikeThisContract';
    }
  | {
      data: number;
      kind: 'CallerBalanceNotEnough';
    }
  | {
      kind: 'OnlyOwnerCanEvolve';
    }
  | {
      kind: 'EvolveNotAllowed';
    }
  | {
      data: string;
      kind: 'WalletHasNoBalanceDefined';
    };
